image: docker:latest

# This is a basic CI/CD pipeline configuration for GitLab integrated with Docker.

stages:
  - build
  - deploy

variables:
  # Set your Docker image name and tag here
  DOCKER_IMAGE: genericui
  DOCKER_TAG: latest

# Define the job to build the Docker image
build_image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker login -u superuser -p Tech@123 $CI_REGISTRY
    - docker push genericui:latest

# Define the job to deploy the Docker image
deploy_image:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u superuser -p Tech@123 $CI_REGISTRY
    - docker pull genericui:latest
    # Add your deployment steps here, such as deploying the image to a server or a Kubernetes cluster.
