image: docker:latest

services:
  - docker:latest

stages:
  # - Login
  - Build
  - Push
  # - Logout

variables:
  CONTAINER_TEST_IMAGE: generic-hmis:test

# login_job:
#   stage: Login
#   tags:
#     - docker
#   script:
#     - docker login -u tech1 -p tech@123 registry.techjivaaindia.in:5005/administrators/generic-hmis 

build_job:
  stage: Build
  tags:
    - docker
  script:
    - docker build -t generic-hmis:test .

push_job:
  stage: Push
  tags:
    - docker
  script:
    - docker push generic-hmis:test

# logout_job:
#   stage: Logout
#   tags:
#     - docker
#   script:
#     - docker logout registry.techjivaaindia.in:5005/administrators/generic-hmis
