image: node:16.14.2-bullseye

services:
  - docker:dind

stages:
  - build
  - deploy


build:
  stage: build
  script:
    - docker login gitlab.techjivaaindia.in
    


deploy:
  stage: deploy
  script:
    - docker build -t gitlab.techjivaaindia.in/administrators/generic-hmis
    - docker push gitlab.techjivaaindia.in/administrators/generic-hmis
