image: docker:latest

services:
  - docker:latest

stages:
  - Build

variables:
  CONTAINER_TEST_IMAGE: generic-hmis:latest

build_job:
  stage: Build
  script:
    - docker login registry.techjivaaindia.in:5005
    - docker login -u tech1 -p tech@123 registry.techjivaaindia.in:5005/administrators/generic-hmis 
    - docker build -t registry.techjivaaindia.in:5005/administrators/generic-hmis .
    - docker push generic-hmis:test
    - docker logout

stages:
  - Login
  - Build
  - Push
  # - Logout

variables:
  CONTAINER_TEST_IMAGE: generic-hmis:test

login_job:
  stage: Login
  tags:
    - docker
  script:
    - docker login registry.techjivaaindia.in:5005
    - docker login -u tech1 -p tech@123 registry.techjivaaindia.in:5005/administrators/generic-hmis 

build_job:
  stage: Build
  tags:
    - docker
  script:
    - docker build -t registry.techjivaaindia.in:5005/administrators/generic-hmis .

push_job:
  stage: Push
  tags:
    - docker
  script:
    - docker push registry.techjivaaindia.in:5005/administrators/generic-hmis

# logout_job:
#   stage: Logout
#   tags:
#     - docker
#   script:
#     - docker logout registry.techjivaaindia.in:5005/administrators/generic-hmis
