image: docker:latest

services:
  - docker:latest

stages:
  # - Login
  - Build
  - Push
  # - Logout

variables:
  CONTAINER_TEST_IMAGE: generic-hmis:test

# login_job:
#   stage: Login
#   tags:
#     - docker
#   script:
#     - docker login -u tech1 -p tech@123 gitlab.techjivaaindia.in/administrators/generic-hmis 

build_job:
  stage: Build
  tags:
    - docker
  script:
    -  docker buildx build  -t  generic-hmis  gitlab.techjivaaindia.in/administrators/generic-hmis  

push_job:
  stage: Push
  tags:
    - docker
  script:
    - docker push gitlab.techjivaaindia.in/administrators/generic-hmis

# logout_job:
#   stage: Logout
#   tags:
#     - docker
#   script:
#     - docker logout gitlab.techjivaaindia.in/administrators/generic-hmis
