export const data =
    [
        {
            "id": "1000",
            "code": "f230fkgjktjkjktjksfkv;fjbkltjligjlktjl gjhthgjtlijgtkjljluliueivujkh0g3 f230fkgjktjkjktjksfkv;fjbkltjligjlktjl gjhthgjtlijgtkjljluliueivujkh0g3f230fkgjktjkjktjksfkv;fjbkltjligjlktjl gjhthgjtlijgtkjljluliueivujkh0g3f230fkgjktjkjktjksfkv;fjbkltjligjlktjl gjhthgjtlijgtkjljluliueivujkh0g3f230fkgjktjkjktjksfkv;fjbkltjligjlktjl gjhthgjtlijgtkjljluliueivujkh0g3",
            "name":"Satyam",
            "description": "Product",
            "profilePic": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
            "price": 1414,
            "category": "Accessories",
            "quantity": 24,
            "inventoryStatus": "INSTOCK",
            "rating": 5,
            "date":"2023-05-02",
            "is_Active": false,
        },
        {
            "id": "1001",
            "code": "djcdj",
            "name": "Black Watch",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
            "price": 72,
            "category": "Accessories",
            "quantity": 61,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1002",
            "code": "zz21cz3c1",
            "name": "Blue Band",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
            "price": 79,
            "category": "Fitness",
            "quantity": 2,
            "inventoryStatus": "LOWSTOCK",
            "ratig": 3,
            "date":"2023-05-02",
            "is_Active": false
        },
        {
            "id": "1003",
            "code": "244wgerg2",
            "name": "Blue T-Shirt",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
            "price": 29,
            "category": "Clothing",
            "quantity": 25,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1004",
            "code": "h456wer53",
            "name": "Bracelet",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
            "price": 15,
            "category": "Accessories",
            "quantity": 73,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1005",
            "code": "av2231fwg",
            "name": "Brown Purse",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
            "price": 120,
            "category": "Accessories",
            "quantity": 0,
            "inventoryStatus": "OUTOFSTOCK",
            "date":"2023-05-02",
            "is_Active": true
            
        },
        {
            "id": "1006",
            "code": "bib36pfvm",
            "name": "Chakra Bracelet",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
            "price": 32,
            "category": "Accessories",
            "quantity": 5,
            "inventoryStatus": "LOWSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1007",
            "code": "mbvjkgip5",
            "name": "Galaxy Earrings",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
            "price": 34,
            "category": "Accessories",
            "quantity": 23,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1008",
            "code": "vbb124btr",
            "name": "Game Controller",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
            "price": 99,
            "category": "Electronics",
            "quantity": 2,
            "inventoryStatus": "LOWSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1009",
            "code": "cm230f032",
            "name": "Gaming Set",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
            "price": 299,
            "category": "Electronics",
            "quantity": 63,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1010",
            "code": "plb34234v",
            "name": "Gold Phone Case",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
            "price": 24,
            "category": "Accessories",
            "quantity": 0,
            "inventoryStatus": "OUTOFSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1011",
            "code": "4920nnc2d",
            "name": "Green Earbuds",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
            "price": 89,
            "category": "Electronics",
            "quantity": 23,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1012",
            "code": "250vm23cc",
            "name": "Green T-Shirt",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
            "price": 49,
            "category": "Clothing",
            "quantity": 74,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1013",
            "code": "fldsmn31b",
            "name": "Grey T-Shirt",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
            "price": 48,
            "category": "Clothing",
            "quantity": 0,
            "inventoryStatus": "OUTOFSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1014",
            "code": "waas1x2as",
            "name": "Headphones",
            "description": "Product Description",
            "profilePic": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
            "price": 175,
            "category": "Electronics",
            "quantity": 8,
            "inventoryStatus": "LOWSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1015",
            "code": "vb34btbg5",
            "name": "Light Green T-Shirt",
            "description": "Product Description",
            "profilePic": "",
            "price": 49,
            "category": "Clothing",
            "quantity": 34,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1016",
            "code": "k8l6j58jl",
            "name": "Lime Band",
            "description": "Product Description",
            "profilePic": undefined,
            "price": 79,
            "category": "Fitness",
            "quantity": 12,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1017",
            "code": "v435nn85n",
            "name": "Mini Speakers",
            "description": "Product Description",
            "profilePic": null,
            "price": 85,
            "category": "Clothing",
            "quantity": 42,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1018",
            "code": "09zx9c0zc",
            "name": "Painted Phone Case",
            "description": "Product Description",
            "profilePic": "",
            "price": 56,
            "category": "Accessories",
            "quantity": 41,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1019",
            "code": "mnb5mb2m5",
            "name": "Pink Band",
            "description": "Product Description",
            "profilePic": "",
            "price": 79,
            "category": "Fitness",
            "quantity": 63,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1020",
            "code": "r23fwf2w3",
            "name": "Pink Purse",
            "description": "Product Description",
            "profilePic": "",
            "price": 110,
            "category": "Accessories",
            "quantity": 0,
            "inventoryStatus": "OUTOFSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1021",
            "code": "pxpzczo23",
            "name": "Purple Band",
            "description": "Product Description",
            "profilePic": "",
            "price": 79,
            "category": "Fitness",
            "quantity": 6,
            "inventoryStatus": "LOWSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1022",
            "code": "2c42cb5cb",
            "name": "Purple Gemstone Necklace",
            "description": "Product Description",
            "profilePic": "",
            "price": 45,
            "category": "Accessories",
            "quantity": 62,
            "inventoryStatus": "INSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        },
        {
            "id": "1023",
            "code": "5k43kkk23",
            "name": "Purple T-Shirt",
            "description": "Product Description",
            "profilePic": "",
            "price": 49,
            "category": "Clothing",
            "quantity": 2,
            "inventoryStatus": "LOWSTOCK",
            "date":"2023-05-02",
            "is_Active": true
        }
    ]


