import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { MasterPageComponent } from './master-page.component';

const routes: Routes = [
  {
    path: '', component: MasterPageComponent,
    children: [
      { path: 'role-management', loadChildren: () => import('./../role-management/role-management.module').then(m => m.RoleManagementModule) },
      { path: 'master-module', loadChildren: () => import('./../master-module/master-module.module').then(m => m.MasterModuleModule) },
      { path: 'sub-module', loadChildren: () => import('./../sub-module/sub-module.module').then(m => m.SubModuleModule) },
      { path: 'organization', loadChildren:()=> import('./../organization/organizationModule').then(m=>m.OrganizationModule)},
      { path: 'registration-form', loadChildren:()=> import('./../registration-form/registration-form.module').then(m=>m.RegistrationFormModule)},

      { path: 'home', loadChildren: () => import('./../home/home.module').then(m => m.HomeModule)},
      { path: 'emergency-quick-registration', loadChildren: () => import('./../emergency-quick-registration/emergency-quick-registration.module').then(m => m.EmergencyQuickRegistrationModule)},
      { path: 'er-patient-list', loadChildren: () => import('./../er-patient-list/er-patient-list.module').then(m => m.ErPatientListModule)},
      { path: 'er-discharge-patient-list', loadChildren: () => import('./../er-discharge-patient-list/er-discharge-patient-list.module').then(m => m.ErDischargePatientListModule)},
      { path: 'cancel-patient-list', loadChildren: () => import('./../cancel-patient-list/cancel-patient-list.module').then( m => m.CancelPatientListModule)},
      { path: 'all-masters', loadChildren: () => import('./../all-masters/all-masters.module').then( m => m.AllMastersModule)},
      { path: 'create-abha-id', loadChildren: () => import('./../create-abha-id/create-abha-id.module').then( m => m.CreateAbhaIdModule)},
      { path: 'patient-list', loadChildren: () => import('./../patient-list/patient-list.module').then( m => m.PatientListModule)},
      { path: 'patients-waiting', loadChildren: () => import('./../patients-waiting/patients-waiting.module').then( m => m.PatientsWaitingModule)},
      { path: 'token-display', loadChildren: () => import('./../token-display/token-display.module').then( m => m.TokenDisplayModule)},
      { path: 'quick-patient-reg-visit', loadChildren: () => import('./../quick-patient-reg-visit/quick-patient-reg-visit.module').then( m => m.QuickPatientRegVisitModule)},
      { path: 'queue', loadChildren: () => import('./../queue/queue.module').then( m => m.QueueModule)},
      { path: 'appointment', loadChildren: () => import('./../appointment/appointment.module').then( m => m.AppointmentModule)},
      { path: 'appointment-list', loadChildren: () => import('./../appointment-list/appointment-list.module').then( m => m.AppointmentListModule)},
      { path: 'registration', loadChildren: () => import('./../registration/registration.module').then( m => m.RegistrationModule)},
      { path: 'registration-list', loadChildren: () => import('./../registration-list/registration-list.module').then( m => m.RegistrationListModule)},
      { path: 'opd-visit-list', loadChildren: () => import('./../opd-visit-list/opd-visit-list.module').then( m => m.OpdVisitListModule)},
      { path: 'feedback-visit-list', loadChildren: () => import('./../feedback-visit-list/feedback-visit-list.module').then( m => m.FeedbackVisitListModule)},
      { path: 'list-of-registration-report', loadChildren: () => import('./../list-of-registration-report/list-of-registration-report.module').then( m => m.ListOfRegistrationReportModule)},
      { path: 'list-of-visit-report', loadChildren: () => import('./../list-of-visit-report/list-of-visit-report.module').then( m => m.ListOfVisitReportModule)},
      { path: 'haspathal-report', loadChildren: () => import('./../haspathal-report/haspathal-report.module').then( m => m.HaspathalReportModule)},
      { path: 'ipd-quick-registration', loadChildren: () => import('./../ipd-quick-registration/ipd-quick-registration.module').then( m => m.IpdQuickRegistrationModule)},
      { path: 'discharge', loadChildren: () => import('./../discharge/discharge.module').then( m => m.DischargeModule)},
      { path: 'discharge-summary', loadChildren: () => import('./../discharge-summary/discharge-summary.module').then( m => m.DischargeSummaryModule)},
      { path: 'ot-schedule', loadChildren: () => import('./../ot-schedule/ot-schedule.module').then( m => m.OtScheduleModule)},
      { path: 'ot-request', loadChildren: () => import('./../ot-request/ot-request.module').then( m => m.OtRequestModule)},
      { path: 'ot-schedule-list', loadChildren: () => import('./../ot-schedule-list/ot-schedule-list.module').then( m => m.OtScheduleListModule)},
      { path: 'labour-room-request', loadChildren: () => import('./../labour-room-request/labour-room-request.module').then( m => m.LabourRoomRequestModule)},
      { path: 'labour-room-schedule', loadChildren: () => import('./../labour-room-schedule/labour-room-schedule.module').then( m => m.LabourRoomScheduleModule)},
      { path: 'labour-room-details', loadChildren: () => import('./../labour-room-details/labour-room-details.module').then( m => m.LabourRoomDetailsModule)},
      { path: 'schedule-list', loadChildren: () => import('./../schedule-list/schedule-list.module').then( m => m.ScheduleListModule)},
      { path: 'labour-room-finalized-list', loadChildren: () => import('./../labour-room-finalized-list/labour-room-finalized-list.module').then( m => m.LabourRoomFinalizedListModule)},
      { path: 'nursing-console', loadChildren: () => import('./../nursing-console/nursing-console.module').then( m => m.NursingConsoleModule)},
      { path: 'add-charges-for-nurse-doctor', loadChildren: () => import('./../add-charges-for-nurse-doctor/add-charges-for-nurse-doctor.module').then( m => m.AddChargesForNurseDoctorModule)},
      { path: 'inpatient-issue', loadChildren: () => import('./../inpatient-issue/inpatient-issue.module').then( m => m.InpatientIssueModule)},
      { path: 'bill-list', loadChildren: () => import('./../bill-list/bill-list.module').then( m => m.BillListModule)},
      { path: 'cancelled-bill-list', loadChildren: () => import('./../cancelled-bill-list/cancelled-bill-list.module').then( m => m.CancelledBillListModule)},
      { path: 'bill-refund', loadChildren: () => import('./../bill-refund/bill-refund.module').then( m => m.BillRefundModule)},
      { path: 'advance', loadChildren: () => import('./../advance/advance.module').then( m => m.AdvanceModule)},
      { path: 'company-bill-settlement', loadChildren: () => import('./../company-bill-settlement/company-bill-settlement.module').then( m => m.CompanyBillSettlementModule)},
      { path: 'opening-balance', loadChildren: () => import('./../opening-balance/opening-balance.module').then( m => m.OpeningBalanceModule)},
      { path: 'item-enquiry', loadChildren: () => import('./../item-enquiry/item-enquiry.module').then( m => m.ItemEnquiryModule)},
      { path: 'quotation', loadChildren: () => import('./../quotation/quotation.module').then( m => m.QuotationModule)},
      { path: 'generate-po', loadChildren: () => import('./../generate-po/generate-po.module').then( m => m.GeneratePoModule)},
      { path: 'good-receive-note', loadChildren: () => import('./../good-receive-note/good-receive-note.module').then( m => m.GoodReceiveNoteModule)},
      { path: 'return-items', loadChildren: () => import('./../return-items/return-items.module').then( m => m.ReturnItemsModule)},
      { path: 'current-stock', loadChildren: () => import('./../current-stock/current-stock.module').then( m => m.CurrentStockModule)},
      { path: 'stock-consumption', loadChildren: () => import('./../stock-consumption/stock-consumption.module').then( m => m.StockConsumptionModule)},
      { path: 'adjust-stock', loadChildren: () => import('./../adjust-stock/adjust-stock.module').then( m => m.AdjustStockModule)},
      { path: 'scrap-sale', loadChildren: () => import('./../scrap-sale/scrap-sale.module').then( m => m.ScrapSaleModule)},
      { path: 'pharmacy-pending-list', loadChildren: () => import('./../pharmacy-pending-list/pharmacy-pending-list.module').then( m => m.PharmacyPendingListModule)},
      { path: 'pharmacy-sale', loadChildren: () => import('./../pharmacy-sale/pharmacy-sale.module').then( m => m.PharmacySaleModule)},
      { path: 'pharmacy-bill-list', loadChildren: () => import('./../pharmacy-bill-list/pharmacy-bill-list.module').then( m => m.PharmacyBillListModule)},
      { path: 'pharmacy-queue', loadChildren: () => import('./../pharmacy-queue/pharmacy-queue.module').then( m => m.PharmacyQueueModule)},
      { path: 'pharmacy-sale-return', loadChildren: () => import('./../pharmacy-sale-return/pharmacy-sale-return.module').then( m => m.PharmacySaleReturnModule)},
      { path: 'pharmacy-bill-settlement', loadChildren: () => import('./../pharmacy-bill-settlement/pharmacy-bill-settlement.module').then( m => m.PharmacyBillSettlementModule)},
      { path: 'pharmacy-bill-edit', loadChildren: () => import('./../pharmacy-bill-edit/pharmacy-bill-edit.module').then( m => m.PharmacyBillEditModule)},
      { path: 'nursing-indent', loadChildren: () => import('./../nursing-indent/nursing-indent.module').then( m => m.NursingIndentModule)},
      { path: 'ambulance-requisition', loadChildren: () => import('./../ambulance-requisition/ambulance-requisition.module').then( m => m.AmbulanceRequisitionModule)},
      { path: 'opd-application-form', loadChildren: () => import('./../opd-application-form/opd-application-form.module').then( m => m.OpdApplicationFormModule)},
      { path: 'ipd-application-form', loadChildren: () => import('./../ipd-application-form/ipd-application-form.module').then( m => m.IpdApplicationFormModule)},
      { path: 'emg-application-form', loadChildren: () => import('./../emg-application-form/emg-application-form.module').then( m => m.EmgApplicationFormModule)},

      { path: 'new-admission-request', loadChildren: () => import('./../new-admission-request/new-admission-request.module').then( m => m.NewAdmissionRequestModule)},
      { path: 'list-of-admission-request', loadChildren: () => import('./../list-of-admission-request/list-of-admission-request.module').then( m => m.ListOfAdmissionRequestModule)},
      { path: 'admission-list', loadChildren: () => import('./../admission-list/admission-list.module').then( m => m.AdmissionListModule)},
      { path: 'discharge-list', loadChildren: () => import('./../discharge-list/discharge-list.module').then( m => m.DischargeListModule)},
      { path: 'admission-cancel-list', loadChildren: () => import('./../admission-cancel-list/admission-cancel-list.module').then( m => m.AdmissionCancelListModule)},
      { path: 'bed-transfer', loadChildren: () => import('./../bed-transder/bed-transder.module').then( m => m.BedTransderModule)},
      { path: 'under-maintenance', loadChildren: () => import('./../under-maintenance/under-maintenance.module').then( m => m.UnderMaintenanceModule)},
      { path: 'graphical-view', loadChildren: () => import('./../graphical-view/graphical-view.module').then( m => m.GraphicalViewModule)},
      { path: 'ipd-admission-report', loadChildren: () => import('./../ipd-adimission-report/ipd-adimission-report.module').then( m => m.IpdAdimissionReportModule)},
      { path: 'birth-certificate', loadChildren: () => import('./../birth-certificate/birth-certificate.module').then( m => m.BirthCertificateModule)},
      { path: 'still-birth-certificate', loadChildren: () => import('./../still-birth-certificate/still-birth-certificate.module').then( m => m.StillBirthCertificateModule)},
      { path: 'death-certificate', loadChildren: () => import('./../death-certificate/death-certificate.module').then( m => m.DeathCertificateModule)},
      { path: 'post-mortem-certificate', loadChildren: () => import('./../post-mortem-certificate/post-mortem-certificate.module').then( m => m.PostMortemCertificateModule)},
    ],
    // canActivate: [AuthGuardGuard]
  }];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class MasterPageRoutingModule { }
